### ISSUE TITLE
Issue while launching just after building from source with ruby

### ISSUE THREAD

**Issue by cppxaxa** [pannous/english-script#9]
In ubuntu 18.04, just after building english-script from the source with ruby tools, if we launch the "angle" executable, I faced the following issue

~/english-script$ ./bin/angle
Traceback (most recent call last):
        3: from /home/cppxaxa/english-script/src/core/repl-shell.rb:1:in `<main>'
        2: from /home/cppxaxa/english-script/src/core/repl-shell.rb:1:in `require_relative'
        1: from /home/cppxaxa/english-script/src/core/english-parser.rb:7:in `<top (required)>'
/home/cppxaxa/english-script/src/core/english-parser.rb:7:in `require_relative': cannot load such file -- /home/cppxaxa/english-script/src/core/interpretation (LoadError)

**Comment by cppxaxa** [comment]
On checking out the paths, src/core/Interpretation.rb can be found. Since Linux is case-sensitive, the name of the file needs to be "interpretation.rb" and the shell will start working
